import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {NullEngine,Scene,Vector3} from '@babylonjs/core';
import {World} from '../src/map/World';
import {MAP,OBJECTIVES,RAMPS,SURFACE_CONNECTIONS,laneZ} from '../src/map/MapLayout';
import {groundLane,rampFloor} from '../src/map/Topology';
const engine=new NullEngine(),scene=new Scene(engine),world=new World(scene);world.buildVillage();const graph=world.tactical!;
const surface=(x:number,z:number)=>new Vector3(x,world.terrain.height(x,z),z);
function reachable(a:Vector3,b:Vector3,allowCross:boolean){const start=graph.nearest(a),end=graph.nearest(b),seen=new Set([start]),queue=[start];assert.ok(start>=0&&end>=0);for(let i=0;i<queue.length;i++){const id=queue[i];if(id===end)return true;for(const edge of graph.edges[id]){const n=graph.nodes[edge.to];if(n.level==='tunnel'||seen.has(n.id)||!allowCross&&groundLane(n.position.z)!==groundLane(graph.nodes[id].position.z))continue;seen.add(n.id);queue.push(n.id);}}return false;}
after(()=>{scene.dispose();engine.dispose();});
test('authored elevations, objective positions and protected spawn court remain within 180 × 90',()=>{assert.equal(MAP.width,180);assert.equal(MAP.depth,90);assert.deepEqual(OBJECTIVES.map(p=>[p.x,p.y,p.z]),[[-48,0,0],[0,1,0],[48,0,0]]);assert.equal(world.terrain.height(46,32),4);assert.ok(world.terrain.height(20,-28)<-1.3);for(const x of [-82,82])assert.ok(world.canStand(x,0,0));assert.ok(world.blocked(new Vector3(-82,1.56,0),new Vector3(82,1.56,0)));});
test('each of the three surface lanes traverses end to end without any tunnel or lane change',()=>{for(const lane of ['main','north','south'] as const)assert.ok(reachable(surface(-82,laneZ(lane,-82)),surface(82,laneZ(lane,82)),false),lane);});
test('exactly two surface transfers connect lanes; removing them separates all three',()=>{assert.equal(SURFACE_CONNECTIONS.length,2);const points=[surface(0,0),surface(0,31),surface(20,-28)];for(let i=0;i<points.length;i++)for(let j=i+1;j<points.length;j++){assert.ok(reachable(points[i],points[j],true));assert.equal(reachable(points[i],points[j],false),false);}for(const p of SURFACE_CONNECTIONS)assert.ok(graph.walkableLink(surface(p.x,p.z-2),surface(p.x,p.z+2)));});
test('physical dividers stop standing, crouching and jumping away from the two gates',()=>{for(const p of SURFACE_CONNECTIONS)for(let x=-88;x<=88;x+=.5){if(Math.abs(x-p.x)<p.width/2+.6)continue;const y=world.terrain.height(x,p.z);for(const jump of [0,.85])assert.equal(world.canStand(x,y+jump,p.z,.33,1.2),false,`${x},${p.z},${jump}`);}});
test('every underground graph edge agrees with standing collision and floor height',()=>{let edges=0;for(const n of graph.nodes)for(const edge of graph.edges[n.id])if(edge.to>n.id&&(n.level==='tunnel'||graph.nodes[edge.to].level==='tunnel')){assert.ok(graph.walkableLink(n.position,graph.nodes[edge.to].position),`${n.position} -> ${graph.nodes[edge.to].position}`);edges++;}assert.ok(edges>500);});
test('all seven mouths join the central underground room with traversable ramps below 30 degrees',()=>{assert.equal(RAMPS.length,7);for(const r of RAMPS){const lip=surface(...r.lip),bottom=new Vector3(r.bottom[0],-4,r.bottom[1]);assert.ok(graph.find(new Vector3(0,-4,0),lip,'tunnel').length,r.id);assert.ok(graph.find(lip,new Vector3(0,-4,0),'tunnel').length,r.id);assert.ok(Math.atan2(lip.y+4,Math.hypot(lip.x-bottom.x,lip.z-bottom.z))*180/Math.PI<30);assert.equal(rampFloor(r,bottom.x,bottom.z,world.terrain.height),-4);}});
test('main-street sampled sight lines stay within 55 metres, and high ground cannot cover A B C at once',()=>{const positions:Vector3[]=[];for(let x=-74;x<=74;x+=2)for(const offset of [-2,0,2]){const p=surface(x,laneZ('main',x)+offset);if(world.canStand(p.x,p.y,p.z))positions.push(p.add(new Vector3(0,1.56,0)));}for(let i=0;i<positions.length;i++)for(let j=i+1;j<positions.length;j++)if(Vector3.Distance(positions[i],positions[j])>55)assert.ok(world.blocked(positions[i],positions[j]));for(let x=-80;x<=80;x+=2)for(const offset of [-3,0,3]){const p=surface(x,laneZ('north',x)+offset);if(!world.canStand(p.x,p.y,p.z))continue;assert.ok(OBJECTIVES.some(o=>world.blocked(p.add(new Vector3(0,1.56,0)),new Vector3(o.x,o.y+1.4,o.z))));}});
test('all explicit cover and peek positions remain reachable',()=>{assert.ok(world.coverPoints.length>=8);for(const p of world.coverPoints){assert.ok(world.canStand(p.position.x,p.position.y,p.position.z));assert.ok(graph.walkableLink(p.position,p.peek));}});
