import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const seconds=Number(process.env.SOAK_SECONDS||900),url=process.env.TEST_URL||'http://localhost:5173',name=process.env.SOAK_NAME||'soak';
await mkdir('test-results',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-precise-memory-info','--disable-background-timer-throttling']});const page=await browser.newPage({viewport:{width:1920,height:1080}});const errors=[];page.on('crash',()=>errors.push('PAGE_CRASH'));page.on('pageerror',e=>errors.push(e.message));
await page.goto(url);await page.waitForFunction(()=>window.__game?.scene.isReady());await page.locator('#start').click();
await page.evaluate(()=>{const g=window.__game;g.started=true;g.paused=false;g.hud.menu.hidden=true;const original=g.step.bind(g);window.__soak={matches:[],steps:0,gameSeconds:0};g.step=(dt)=>{window.__soak.steps++;window.__soak.gameSeconds+=dt;original(dt);if(g.match.winner){window.__soak.matches.push({winner:g.match.winner,time:g.time,tickets:{...g.match.tickets}});g.reset();g.started=true;g.paused=false;g.hud.menu.hidden=true;}};g.player.onLock=()=>{};});
const started=Date.now(),samples=[];
try{while(Date.now()-started<seconds*1000){await new Promise(r=>setTimeout(r,Math.min(30000,seconds*1000-(Date.now()-started))));const sample=await page.evaluate(()=>({stats:window.__game.diagnostics.snapshot(),soak:window.__soak}));samples.push({...sample,elapsed:(Date.now()-started)/1000});await writeFile(`test-results/${name}.json`,JSON.stringify({seconds,samples,errors,running:true},null,2));console.log(JSON.stringify({elapsed:Math.round((Date.now()-started)/1000),...sample.stats,matches:sample.soak.matches.length}));if(errors.length)break;}
 const result=await page.evaluate(()=>({stats:window.__game.diagnostics.snapshot(),samples:window.__game.diagnostics.samples,errors:window.__game.diagnostics.errors,soak:window.__soak}));const stable=['meshes','materials','textures','ai','transformNodes','effectPool'].every(k=>samples.every(s=>s.stats[k]===samples[0].stats[k]));const report={seconds,wallSeconds:(Date.now()-started)/1000,stable,result,samples,errors,running:false};await writeFile(`test-results/${name}.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({done:true,stable,wallSeconds:report.wallSeconds,matches:result.soak.matches,errors}));if(!stable||errors.length||result.errors.length||result.soak.gameSeconds<seconds*.9)process.exitCode=1;
}finally{await browser.close();}
