import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:5173');await page.waitForFunction(()=>window.__game?.scene.isReady());
const result=await page.evaluate(async()=>{
 const {GROUND_PORTALS,allowedSurfaceEdge,groundLane}=await import('/src/map/Topology.ts');const g=window.__game,w=g.world,graph=w.tactical,V=g.player.position.constructor;g.engine.stopRenderLoop();
 const leaks=[],edgeLeaks=[],portals=new Set();let sampled=0;
 for(const p of GROUND_PORTALS)for(let x=-88.5;x<=88.5;x+=.25){if(Math.abs(x-p.x)<p.width/2+.4)continue;for(const side of [-1,1])for(const jump of [0,.845]){const pos=new V(x,w.terrain.height(x,p.z+side*1.5)+jump,p.z+side*1.5);for(let i=0;i<60;i++)w.move(pos,0,-side*.05,1.7,jump===0);sampled++;if((pos.z-p.z)*side<-.7)leaks.push({x,z:p.z,side,jump,end:pos.asArray()});}}
 for(const n of graph.nodes)if(n.level!=='tunnel')for(const e of graph.edges[n.id]){const b=graph.nodes[e.to];if(b.level==='tunnel')continue;if(!allowedSurfaceEdge(n.position,b.position))edgeLeaks.push([n.id,b.id]);if(groundLane(n.position.z)!==groundLane(b.position.z)){const p=GROUND_PORTALS.find(p=>Math.abs(n.position.x-p.x)<2&&Math.abs(n.position.z-p.z)<=2);if(p)portals.add(p.id);}}
 const gates=GROUND_PORTALS.map(p=>{const pos=new V(p.x,w.terrain.height(p.x,p.z-2),p.z-2);for(let i=0;i<90;i++)w.move(pos,0,.05);return {id:p.id,passed:pos.z>p.z+1.5};});
 const seedPositions=[[-40,2.4,22],[0,1.2,0],[30,-1.2,-38]],seeds=seedPositions.map(p=>graph.nearest(new V(...p),false));
 const reachable=(start,allowTunnel)=>{const seen=new Set([start]),queue=[start];for(let i=0;i<queue.length;i++)for(const e of graph.edges[queue[i]]){const a=graph.nodes[queue[i]],b=graph.nodes[e.to];if(!allowTunnel&&(a.level==='tunnel'||b.level==='tunnel'))continue;if(a.level!=='tunnel'&&b.level!=='tunnel'&&groundLane(a.position.z)!==groundLane(b.position.z))continue;if(!seen.has(e.to)){seen.add(e.to);queue.push(e.to);}}return seen;};
 const disconnected=seeds.every((s,i)=>seeds.every((t,j)=>i===j||!reachable(s,false).has(t))),undergroundReconnects=seeds.every(s=>seeds.every(t=>reachable(s,true).has(t)));
 const undergroundEdges=[];for(const n of graph.nodes)for(const e of graph.edges[n.id]){const b=graph.nodes[e.to];if(n.id<b.id&&(n.level==='tunnel'||b.level==='tunnel')&&!graph.walkableLink(n.position,b.position))undergroundEdges.push({a:n.position.asArray(),b:b.position.asArray()});}
 const initial=g.scene.meshes.length;document.dispatchEvent(new KeyboardEvent('keydown',{code:'F3'}));const debug=g.scene.meshes.length;for(let i=0;i<20;i++)document.dispatchEvent(new KeyboardEvent('keydown',{code:'F3'}));const debugReuse=g.scene.meshes.length===debug;document.dispatchEvent(new KeyboardEvent('keydown',{code:'F3'}));
 const sightBlocked=w.blocked(new V(-64,-2.6,-25),new V(-64,-2.6,3))&&w.blocked(new V(-20,-2.6,-29),new V(64,-2.6,-29));
 return {sampled,leaks,edgeLeaks,portals:[...portals],gates,seeds,disconnected,undergroundReconnects,undergroundEdges,debugMeshes:debug-initial,debugReuse,sightBlocked};
});await mkdir('test-results',{recursive:true});await writeFile('test-results/topology.json',JSON.stringify({result,errors},null,2));console.log(JSON.stringify({result,errors},null,2));await browser.close();if(errors.length||result.leaks.length||result.edgeLeaks.length||result.portals.length!==2||result.gates.some(g=>!g.passed)||!result.disconnected||!result.undergroundReconnects||result.undergroundEdges.length||!result.debugReuse||!result.sightBlocked)process.exit(1);
