import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import {createRequire} from 'node:module';import {NullEngine,Scene,Vector3} from '@babylonjs/core';
const require=createRequire(import.meta.url);const {createCanvas}=require(process.env.CANVAS_MODULE || '@napi-rs/canvas');
(globalThis as any).OffscreenCanvas=class{constructor(w:number,h:number){return createCanvas(w,h);}};
const root=path.resolve(process.argv[2]||'.'),load=(p:string)=>import(pathToFileURL(path.join(root,p)).href);
const {World}=await load('src/map/World.ts'),{Bot}=await load('src/ai/Bot.ts'),{Combat}=await load('src/game/Combat.ts'),{CaptureSystem}=await load('src/capture/CaptureSystem.ts'),{Match}=await load('src/game/Match.ts');
const engine=new NullEngine(),scene=new Scene(engine),w=new World(scene);const init=performance.now();w.buildVillage();const initMs=performance.now()-init;
const bots=Array.from({length:15},(_,i)=>new Bot(i+1,i<7?'cn':'jp',w));const player={id:0,team:'cn',position:new Vector3(-82,0,0),health:100,alive:true,protection:0,respawnAt:0};const actors=[player,...bots],combat=new Combat(w,actors),capture=new CaptureSystem(),match=new Match();let time=0;combat.onDeath=(a:any)=>{a.respawnAt=time+5;a.deadAt=time;match.death(a.team);};bots.forEach(b=>b.onFire=(...args:any[])=>combat.botShoot(...args));capture.onCapture=()=>bots.forEach(b=>b.requestReplan(time));
let seed=1938;Math.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
const slowCalls:any[]=[];
const times:Record<string,{ms:number;calls:number}>={},stack:number[]=[];
function wrap(obj:any,key:string,bucket:string){const old=obj[key];obj[key]=function(...args:any[]){const start=performance.now();stack.push(0);try{return old.apply(this,args);}finally{const elapsed=performance.now()-start,child=stack.pop()!;if(stack.length)stack[stack.length-1]+=elapsed;const s=times[bucket]??={ms:0,calls:0};s.ms+=elapsed-child;s.calls++;if(elapsed>15)slowCalls.push({bucket,key,ms:elapsed,time});}};}
for(const b of bots)wrap(b,'update','AI');if(w.routePlanner)wrap(w.routePlanner,'tick','Pathfinding');else wrap(w.tactical,'find','Pathfinding');wrap(w.tactical,'nearest','NearestWaypoint');wrap(w,'blocked','LOS');wrap(w,'chooseCover','Cover');for(const k of ['move','canStand','floorAt'])wrap(w,k,'CollisionTerrain');if(w.pickStaticRay)wrap(w,'pickStaticRay','Raycast');else wrap(scene,'pickWithRay','Raycast');
const mode=process.argv[3]||'all';if(mode==='no-ai')bots.forEach(b=>b.update=()=>{});if(mode==='no-path'){if(w.routePlanner)w.routePlanner.tick=()=>{};else w.tactical.find=()=>[];}if(mode==='no-los')combat.visible=()=>false;if(mode==='no-cover')w.chooseCover=()=>null;if(mode==='no-collision'){w.canStand=()=>true;}
const frames:number[]=[],cpuStart=process.cpuUsage();const begin=performance.now();
for(let frame=0;frame<7200;frame++){const start=performance.now();time+=1/60;for(const b of bots)if(!b.alive&&time>=b.respawnAt)b.respawn(time);for(const b of bots)b.update(1/60,time,actors,capture.points,(a:any,b:any)=>combat.visible(a,b));w.routePlanner?.tick();capture.update(1/60,actors);match.update(1/60,capture);frames.push(performance.now()-start);}
const elapsed=performance.now()-begin,cpu=process.cpuUsage(cpuStart);frames.sort((a,b)=>a-b);const report={root,mode,initMs,elapsedMs:elapsed,cpuMs:(cpu.user+cpu.system)/1000,simulationSeconds:120,meanFrameMs:frames.reduce((a,b)=>a+b,0)/frames.length,p95:frames[Math.floor(frames.length*.95)],p99:frames[Math.floor(frames.length*.99)],scheduler:w.routePlanner?{pending:w.routePlanner.pending,maxMs:w.routePlanner.maxMs,completed:w.routePlanner.completed}:null,cacheHits:w.tactical.cacheHits,cacheMisses:w.tactical.cacheMisses,searches:w.tactical.searches,collisionCandidateMean:w.collisionCandidates/w.collisionQueries,max:frames.at(-1),obstacles:w.obstacles.length,nodes:w.tactical.nodes.length,edges:w.tactical.edges.reduce((a:number,b:any[])=>a+b.length,0),slowCalls:slowCalls.sort((a,b)=>b.ms-a.ms).slice(0,20),meshes:scene.meshes.length,cover:w.coverPoints.length,times};
fs.mkdirSync('test-results',{recursive:true});fs.writeFileSync(`test-results/cpu-${path.basename(root)}-${mode}.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));scene.dispose();engine.dispose();
